import Head from "next/head";
import { GetStaticProps } from "next";
import { discoverMovies } from "@Services/movieServices";
import { MovieModel } from "@Models/movieModel";

interface HomePageProps {
  movies: Array<MovieModel>;
}

export default function HomePage({ movies }: HomePageProps) {
  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-emerald-300">
        {movies.map((movie) => (
          <div key={movie.id}>{movie.original_title}</div>
        ))}
      </main>

      <footer>footer</footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps<HomePageProps> = async (
  context
) => {
  const movies = await discoverMovies();

  return { props: { movies: movies.results } };
};
