import Head from "next/head";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-20 bg-emerald-300">main</main>

      <footer>footer</footer>
    </div>
  );
}
