name: CI
on:
  push:
    branches:
      - '!main'

jobs:
  lint:
    name: ESLint check
    runs-on: ubuntu-latest

    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs running environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node modules
        run: npm ci

      - name: Run ESLint check
        run: npm run lint